### PR TITLE
Make @NathanReb the new default codeowner.

### PR DESCRIPTION
**Pull request by mjambon**
@NathanReb needs to be made a project member first (see https://github.com/ocaml-community/yojson/issues/68).

### CODE REVIEW

**Comment by pmetzger** [comment]
Are you sure you don't want to leave us on for a month or two with @NathanReb being the primary maintainer during the transition? It would seem like a good idea. That said, if you prefer just having him informed of pull requests etc., the decision is yours.

**Comment by mjambon** [comment]
I'm watching the github repo so I'll get all the conversations in my mailbox. I think that should be good enough to follow what's happening and help out as needed.

**Comment by pmetzger** [comment]
Merged then! And welcome, @NathanReb!

**Comment by NathanReb** [comment]
Thanks!

**Pull request merged**
