### PR TITLE
Add few functions to the utils module

### PR DESCRIPTION
**Pull request by panglesd**
I'm not sure whether this is useful, or if the api is well designed, but it has been requested to add some more function to the Utils module in #54.

What do you think :question:

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Personally I am not much of a fan how partial the functions are - it feels like supplying them is a potential foot-gun to users.

Without these functions users have to match on `` `Assoc`` and get the compiler to warn them if the data is not an `` `Assoc`` (in which case they're also free to throw an exception or return an `Error` `result`), whereas these functions hide the match and just throw an exceptions themselves. Also, if we implement these functions the users have to deal with our implementations of `update`, `filter_map` or `map`.

What I would suggest instead is a function like

```ocaml
let with_assoc ~f = function
  | `Assoc xs -> `Assoc (f xs)
  | otherwise -> otherwise
```

So users can use `Yojson.Util.with_assoc ~f:(List.Assoc.update ...) json` or whatever other function they want to operate on. But even that function feels a bit fragile, because in the failure mode it silently does… nothing.

**Comment by panglesd** [comment]
I agree, I was pretty unsure of the need of such functions. As the type is public everything can be done by the user, in the way they prefer.

I think that your suggestion is good though, except that to make it more consistent with `to_assoc` I would raise an exception in case of not `Assoc` type.
And, I guess that this means that `with_bool`, `with_int`, `with_list`... also have to be implemented?

**Comment by Leonidas-from-XIV** [comment]
Yes, that's somewhat the thing… none of these functions nor their behavior in the non-assoc/non-list/non-bool case is obvious and throwing an exception in the rare case is a great way to get your program to explode with an uncaught exception. We could of course make a function like

```ocaml
let with_list ~f = function
  | `List xs -> Ok (f xs)
  | otherwise -> Error (`Msg "Not a list")
```

but that will require the user to do a pattern match around the call of `with_list` (or, should we choose to use exceptions, an easy to forget try-block) so I think these functions are probably still more annoying than helpful. But that's just my, kinda minimalist, opinion.

**Comment by panglesd** [comment]
Okay, so I close this PR with the following arguments:
- the `Utils` module is not that useful: as the `Safe.t` `Basic.t`, ... are public, the library user can write his own utilities according to his preferences (exceptions, `Result`, unmodified input, ...)
- it is still kept for retro-compatibility, but not expanded as this PR did.

**Pull request closed without merging**
